### ISSUE TITLE
Unable to open Database

### ISSUE THREAD

**Issue by banivyom** [AlgorexHealth/hcc-python#3]
* sqlite:///mit-poster.db
(sqlite3.OperationalError) unable to open database: ../jupyterdemo/claims.db [SQL: "ATTACH '../jupyterdemo/claims.db' as mem;"] (Background on this error at: http://sqlalche.me/e/e3q8)

This is the error that is occurring when I run the first block, what should I do? Please help Asap.

**Comment by Bowiemb** [comment]
How was this solved? @banivyom Thanks!
